### PR TITLE
Remove CharType::Separator and add CharType::Newline, CharType::Semicolon

### PR DESCRIPTION
**Pull request by yamakoud**

### CODE REVIEW

**Comment by yamakoud** [comment]
@yhara 
I've introduced Token::Newline and Token::Semicolon [here](https://github.com/shiika-lang/shiika/pull/534/files).
So I think it's also good to add Newline and Semicolon as CharType.

What do you think about it?

**Comment by yhara** [comment]
@yamakoud Looks good, let's go ahead!

**Comment by yamakoud** [comment]
oops I forgot to request you review this after I opened this PR

**Comment by yamakoud** [comment]
@yhara 
It's happy if you review this.
And sorry for late to request.

**Comment by yhara** [comment]
Merged. Thank you!

**Pull request merged**
